application: wwwoshineye2
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /(about|books|photos|presentations|search|software|google53de00654ebd3aa1)\.html
  static_files: static/\1.html
  upload: static/(about|books|photos|presentations|search|software|google53de00654ebd3aa1)\.html

# This is the folder of pages pointing to experiments
- url: /x
  static_dir: static/x

- url: /subscriptions.xml
  static_files: static/subscriptions.xml
  upload: static/subscriptions.xml

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# This ensures that / renders /theAbode.html but does not do a redirect
- url: (/theAbode.html|/)
  script: main.py

- url: (/\+)
  script: redirect.py